### ISSUE TITLE
Cosmetic changes

### ISSUE THREAD

**Issue by praveen-murali-ind** [bigbinary/neeto-ui#1205]
@praveen-murali-ind _a

Form Elements

- [x] Button - #1204 
- [x] Checkbox - #1207
- [x] Radio - #1208
- [x] Input - #1209
- [x] Textarea - #1210
- [x] Select - #1215
- [x] Email Input - #1211
- [x] Label - #1212
- [x] Dropdown - #1216
- [x] Action Dropdown - #1217
- [x] Date and Time - #1213
- [x] Accordion - #1218
- [x] Avatar - #1219
- [x] Table - #1220
- [x] Pagination - #1222
- [x] PageLoader - #1230
- [x] Switch - no changes
- [x] Tag - no changes
- [x] Tab - no changes
- [x] Color Picker -  #1235 
- [x] Spinner - no changes
- [x] Callout - no changes

Overlays

- [x] Alert - #1227
- [x] Modal - #1223
- [x] Toastr - #1228
- [x] Tooltip - #1229
- [x] Pane - no changes

Layouts

- [x] AppSwitcher - pending
- [x] Menubar - 
- [x] Sidebar - #1231
- [x] Header - #1234
