### ISSUE TITLE
Frontend packages standardization

### ISSUE THREAD

**Issue by amaldinesh7** [bigbinary/neeto-ui#1563]
### Code quality
- [x] ~Use eslint and prettier configuration from wheel. Make sure that lint-staged is correctly configured to cover all files in the package during commit.~
- [x] Use zustand for state management. Remove the use of contexts.

### Dead code removal
- [x] Remove unused configuration files like webpack config from projects which use rollup: example: [neeto-form-frontend](https://github.dev/bigbinary/neeto-form-frontend/blob/main/webpack.config.js)
- [x] Remove commons functions. Remove boilerplate code, that is already present in neeto-commons-frontend: example: [neeto-form-frontend](https://github.dev/bigbinary/neeto-form-frontend/blob/main/src/hooks/useDebounce.js)
- [x] Delete legacy exports & unused code.
Refer #1613 

### Dependency management
- [x] Move dependencies to `devDependencies` this will speed up package installation time. We don't need dependencies as we are serving bundles. Try to move packages to peerDependencies if the package exists on host project too. Refer: [neetoui](https://github.com/bigbinary/neeto-ui/blob/main/package.json), [neeto-commons-frontend](https://github.com/bigbinary/neeto-commons-frontend/blob/main/package.json)
- [x] Audit & remove unused dependencies.

### General enhancements
- [x] Clean up documentation & include exported functions, development & release instructions.
- [x] Have a mechanism to test changes without depending on a host project and yalc: example: [neeto-team-members-frontend](https://github.com/bigbinary/neeto-team-members-frontend/tree/main/example)
Refer #1617 
- [x] Mark function call wrappings of exports as `PURE`. Reference: [arrays.js](https://github.dev/bigbinary/neeto-commons-frontend/blob/f4dba1232a75f325830d6c1285776664f07eefa8/src/pure/arrays.js#L15-L25)
- [x] Have type declaration for all exports: example: [neetoui](https://github.com/bigbinary/neeto-ui/blob/main/index.d.ts)

### Building & releasing
- [x] ~Standardize release process: release on merge. Example: [neetoui](https://github.com/bigbinary/neeto-ui/blob/main/.github/workflows/publish.yml)~
- [x] Use rollup for bundling
- [x] Export ESM bundles

---

### Misc improvements

- [x] #1633
