### ISSUE TITLE
Antd v5 rollout

### ISSUE THREAD

**Issue by ajmaln** [bigbinary/neeto-ui#1825]
- [x] Disabled compliance for neetoUI temporarily
- [x] https://github.com/bigbinary/neeto-commons-backend/issues/2027
- [x] Update the latest version of `neeto-ui` and `antd` in products with direct component usages from `antd` and verify everything is working:
  - [x] neetoMolecules
  - [x] neetoForm - https://github.com/bigbinary/neeto-form-web/pull/7990
  - [x] https://github.com/bigbinary/neeto-form-frontend/pull/282
  - [x] https://github.com/bigbinary/neeto-cal-web/pull/4931
  - [x] https://github.com/bigbinary/neeto-replay-web/pull/3247
  - [x] https://github.com/bigbinary/neeto-quiz-web/pull/3003
  - [x] https://github.com/bigbinary/neeto-wireframe-web/pull/3151
- [x] Enable back the compliance for `neeto-ui` 
- [x] https://github.com/bigbinary/neeto-commons-backend/issues/2102

@ajmaln _a

**Comment by adityamahajan-io** [comment]
@adityamahajan-io _a

**Comment by ajmaln** [comment]
Antd v5 rollout is completed and enabled the compliance for neetoUI and antd package.
