### ISSUE TITLE
NeetoUI - V4 - Beta

### ISSUE THREAD

**Issue by praveen-murali-ind** [bigbinary/neeto-ui#2219]
Part of https://github.com/bigbinary/neeto-engineering-ui-ux/issues/295

Todo

- [ ] https://github.com/bigbinary/neeto-ui/issues/2220
- [ ] https://github.com/bigbinary/neeto-ui/issues/2221
- [ ] https://github.com/bigbinary/neeto-ui/issues/2222
- [ ] https://github.com/bigbinary/neeto-ui/issues/2223
- [ ] https://github.com/bigbinary/neeto-ui/issues/2224

@praveen-murali-ind _a
